In [1]:
import numpy as np

In [3]:
# сохдание массива

data1 = [ [5.2, 3.0, 4.5] , [9.1, 0.1, 0.3] ]
arr1 = np.array(data1)
arr1

array([[5.2, 3. , 4.5],
       [9.1, 0.1, 0.3]])

In [4]:
# количество измерений массива

arr1.ndim

2

In [5]:
# размер массива

arr1.size

6

In [6]:
# форма массива

arr1.shape

(2, 3)

In [7]:
# тип массива

arr1.dtype

dtype('float64')

In [8]:
# количество элементов массива

arr1.itemsize

8

### Рассморим массивы Numpy

In [9]:
# создаём массив из нулей

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# создаём массив из единиц

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
# создаём массив итерированный от 0 до N

np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
# создаём массив итерированный от 0 до 1 с количеством 25

np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [13]:
# единичная матрица

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Операции между массивами и скалярами

In [16]:
arr = np.array([ [1., 2., 3.] , [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [18]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

### Случайные массивы

In [22]:
# рандомный массив заданного размера

np.random.randn(3,2)

array([[-1.62740201,  1.10246887],
       [-1.44980204,  1.23891725],
       [ 0.62519556,  2.27151853]])

In [24]:
# рандомный массив от 0 до 1000 с числом 4

np.random.randint(0, 1000, 4)

array([277, 963, 951, 346])

### Индексирование

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
# обратимся к элементам с 8 по 12

np.arange(15)[8:12]

array([ 8,  9, 10, 11])

In [28]:
# многомерные массивы

array2d = np.array([ [1,2,3], [4,5,6], [7,8,9]])
array2d[2]

array([7, 8, 9])

In [29]:
# образение к определенному элементу

array2d[0, 2]

3

In [30]:
array2d[0][2]

3

In [32]:
# 3-х мерный массив

array3d = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])
array3d[1,1][2]

12

In [34]:
# обращение к части элементов

array3d[:1,:1,1:]

array([[[2, 3]]])

In [35]:
# будевое индексирование

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [37]:
# создание масок

mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [38]:
names[mask]

array(['Bob', 'Will', 'Bob', 'Will'], dtype='<U4')

### Транспонирование массивов

In [41]:
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
array3d.shape

(2, 2, 3)

In [43]:
array3d.T

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [44]:
array3d.T.shape

(3, 2, 2)

###  Поэлементные операции над массивами

Это векторные обёртки вокруг простых функций, которые принимают одно или несколько скалярных значений и порождают один или несколько скалярных результатов

In [46]:
np.sqrt(array3d)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[2.64575131, 2.82842712, 3.        ],
        [3.16227766, 3.31662479, 3.46410162]]])

In [47]:
np.exp(array3d)

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02]],

       [[1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
        [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]])

###  Математические и статистические операции

In [49]:
arr = np.random.randn(5, 4)
arr

array([[ 0.27154685, -0.6498606 ,  0.25069969, -0.34516959],
       [ 0.56414574, -0.67943735, -1.7059242 , -0.69102489],
       [-1.31211143, -1.07402893, -1.63850204, -0.20588566],
       [-0.62596336,  0.42270239,  1.5751369 , -1.86910806],
       [ 1.18400669,  1.31092228, -0.9248189 ,  0.39068352]])

In [50]:
# форма

arr.shape

(5, 4)

In [52]:
# среднее

arr.mean()

-0.2875995480568788

In [54]:
# сумма

arr.sum()

-5.751990961137576

In [55]:
# max element

np.max(arr)

1.5751369038837635

In [58]:
# максимальный элемент по оси 0

arr.sum(axis = 0)

array([ 0.08162448, -0.6697022 , -2.44340856, -2.72050468])

In [59]:
arr = np.array([ [0,1,2], [3,4,5], [6,7,8]])

In [61]:
# кумулятивная сумма с указанием строки

arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [62]:
# кумулятивное произведение с указанием строки

arr.cumprod(axis = 0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

###  Сортировка

In [64]:
arr = np.random.randn(8)
arr

array([ 1.16398739,  0.11517633, -0.51982883,  1.98630474,  0.76111595,
        0.21825865, -0.59807694, -0.96489668])

In [66]:
arr.sort()
arr

array([-0.96489668, -0.59807694, -0.51982883,  0.11517633,  0.21825865,
        0.76111595,  1.16398739,  1.98630474])

In [68]:
arr = np.random.randn(5, 3)
arr

array([[ 1.56184918,  0.20004556,  1.96192741],
       [-0.50671163,  0.44668484, -0.69587303],
       [ 0.56198284, -0.73077022, -1.72186033],
       [ 0.91639371,  0.29417014, -1.34549514],
       [-0.57165057,  0.44958709,  0.65597874]])

In [71]:
# сортировка с указанием оси - 0 (с учётом строк)

arr.sort(0)
arr

array([[-0.57165057, -0.73077022, -1.72186033],
       [-0.50671163,  0.20004556, -1.34549514],
       [ 0.56198284,  0.29417014, -0.69587303],
       [ 0.91639371,  0.44668484,  0.65597874],
       [ 1.56184918,  0.44958709,  1.96192741]])

In [72]:
# сортировка с указанием оси - 1 (с учётом столбцов)

arr.sort(1)
arr

array([[-1.72186033, -0.73077022, -0.57165057],
       [-1.34549514, -0.50671163,  0.20004556],
       [-0.69587303,  0.29417014,  0.56198284],
       [ 0.44668484,  0.65597874,  0.91639371],
       [ 0.44958709,  1.56184918,  1.96192741]])

In [73]:
# возвращает копию

arr = np.random.randn(5, 3)
np.sort(arr)

array([[-0.86350976, -0.66474988,  1.55386502],
       [-0.66518588, -0.15714934,  1.63803628],
       [-0.74612821, -0.30655186, -0.16538026],
       [ 0.1473756 ,  0.68485287,  2.00457904],
       [ 0.01920384,  0.53339461,  0.61335318]])

In [75]:
arr = np.sort(arr)
arr

array([[-0.86350976, -0.66474988,  1.55386502],
       [-0.66518588, -0.15714934,  1.63803628],
       [-0.74612821, -0.30655186, -0.16538026],
       [ 0.1473756 ,  0.68485287,  2.00457904],
       [ 0.01920384,  0.53339461,  0.61335318]])

###  Хранение массивов на диске в двоичном формате

np.save и np.load - основные функции для эффективного сохранения и загрузки данных с диска. По умолчанию массивы хранятся в несжатом двоичном формате в файле с разрешением .npy

In [78]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# сохраняем массив

np.save('some_array', arr)

In [80]:
# загружаем массив

np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Можно сохранить несколько массивов в zip-архиве с помощью функции np.savez, которой массивы передаются в виде именно

In [81]:
np.savez('array_archive.npz', a=arr, b=arr)

In [82]:
arch = np.load('array_archive.npz')

In [83]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Задание

In [90]:
# создаём вектор 

arr = np.linspace(10, 500, 2)

In [94]:
arr = arr**2

In [96]:
arr = arr-234

In [98]:
arr.sum()

249632.0

### Series и Datafreme

### Pandas Series

Структура/объект Series представляет из себя объект, похожий на одномерный массив (питоновский список), но отличительной его чертой является наличие ассоциированных меток таки как индексов, вдоль каждого элемента их списка. Такая особенность превращает его в ассоциированный массив в Python.

In [1]:
import pandas as pd
import numpy as np

In [101]:
my_series = pd.Series([5,6,7,8,9,10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [102]:
my_series.index

RangeIndex(start=0, stop=6, step=1)

In [103]:
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [104]:
my_series2 = pd.Series([5,6,7,8,9,10],
                     index=['a','b','c','d','e','f'])
my_series2

a     5
b     6
c     7
d     8
e     9
f    10
dtype: int64

In [105]:
my_series2.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [106]:
my_series2[4]

9

In [107]:
my_series2[[4]]

e    9
dtype: int64

In [108]:
my_series2['a']

5

In [110]:
mask = my_series2 > 7
mask

a    False
b    False
c    False
d     True
e     True
f     True
dtype: bool

In [111]:
my_series2[mask]

d     8
e     9
f    10
dtype: int64

In [112]:
my_series2[['a','b','f']] = 0
my_series2

a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64

In [113]:
my_series2[(my_series2 > 0)]

c    7
d    8
e    9
dtype: int64

In [114]:
my_series2 > 0

a    False
b    False
c     True
d     True
e     True
f    False
dtype: bool

In [115]:
my_series3 = pd.Series({'a': 5, 'b': 6, 'c': 7, 'd': 8})
my_series3

a    5
b    6
c    7
d    8
dtype: int64

In [116]:
my_series3.name = 'numbers'
my_series3.index.name = 'letters'
my_series3

letters
a    5
b    6
c    7
d    8
Name: numbers, dtype: int64

### Pandas DataFrame

Объект DataFrame лучше всего представить себе в виде обычной таблицы, так как это табличная структура данных. В любой таблице всегда присутствуют строки и столбцы. Столбцами в объектах DataFrame выступают объекты Series, строки которых являяются их непосредственными элементами.

In [4]:
df = pd.DataFrame({
    'city': ['Moscow', 'Krasnodar', 'Belgorod', 'Kazan'],
    'delivery_time': [25, 29, 32, 30],
    'couriers': [11440, 784, 112, 998]
})
df

city  delivery_time  couriers
0     Moscow             25     11440
1  Krasnodar             29       784
2   Belgorod             32       112
3      Kazan             30       998

In [5]:
df.delivery_time

0    25
1    29
2    32
3    30
Name: delivery_time, dtype: int64

In [6]:
type(df.delivery_time)

pandas.core.series.Series

In [8]:
df[['delivery_time']]

delivery_time
0             25
1             29
2             32
3             30

In [9]:
df.index = ['Msc', 'Krd', 'Blg', 'Kzn']
df

city  delivery_time  couriers
Msc     Moscow             25     11440
Krd  Krasnodar             29       784
Blg   Belgorod             32       112
Kzn      Kazan             30       998

### Импорт данных

In [ ]:
# pd.read_csv('filename')
# pd.read_exel('filename')
# pd.read_sql(query, connection_object)
# pd.read_table(filename)
# pd.read_json(json_string)
# pd.read_html(url)
# pd.read_clipboard()
# pd.DataFrame(dict)

In [11]:
ml = pd.read_csv('money_by_brands.csv')
ml.head(2)

ytem_category product_brand  selling_price
0     jewellery        B-2307       181676.0
1     jewellery        B-1517       139164.0

### Если DataFrame не помещается в оперативную память компьютера, его размер очень большой.

In [ ]:
# метод чтение по Чанкам

c_size = 10000

for gm_chunk in pd.read_csv('filename',
                           sep = ',',
                           chunksize=c_size):
    print(gm_chunk.shape)

### Экспорт данных

In [ ]:
# df.to_csv(filename)
# df.to_exel(filename)
# df.to_sql(table_name, connection_object)
# df.to_json(filename)
# df.to_html(filename)
# df.to_clipboard()

### Доступ к данным

Доступ к строкам по индексу возможен несколькими спопобами:

1.  .loc - используется для доступа по строковаой метке
2.  .iloc - используется для доступа по числовому значению (начиная с 0)

In [13]:
df.loc['Msc']

city             Moscow
delivery_time        25
couriers          11440
Name: Msc, dtype: object

In [14]:
df

city  delivery_time  couriers
Msc     Moscow             25     11440
Krd  Krasnodar             29       784
Blg   Belgorod             32       112
Kzn      Kazan             30       998

In [15]:
df.iloc[1]

city             Krasnodar
delivery_time           29
couriers               784
Name: Krd, dtype: object

In [16]:
type(df.iloc[0])

pandas.core.series.Series

In [17]:
# обращение к индексу и колонке одновременно

df.loc[['Msc', 'Kzn'], 'couriers']

Msc    11440
Kzn      998
Name: couriers, dtype: int64

В .loc и .iloc запомнить, что первая часть относится к строкам, вторая - к столбцам

In [18]:
df

city  delivery_time  couriers
Msc     Moscow             25     11440
Krd  Krasnodar             29       784
Blg   Belgorod             32       112
Kzn      Kazan             30       998

In [20]:
df.iloc[[0,1] , [1]]

delivery_time
Msc             25
Krd             29

In [21]:
# отбор по маске

df[df.delivery_time > 30][['city', 'couriers']]

city  couriers
Blg  Belgorod       112

In [24]:
# более сложный отбор по маске с условием
# > 25 или Москва

df[(df.delivery_time >= 25) | (df.city == 'Msc')][['city', 'delivery_time']]

city  delivery_time
Msc     Moscow             25
Krd  Krasnodar             29
Blg   Belgorod             32
Kzn      Kazan             30

In [26]:
# или маска в виде фильтра

filters = (df.city == 'Moscow')
df[filters]

city  delivery_time  couriers
Msc  Moscow             25     11440

In [40]:
# создание новой колонки 

df['delivery_time_hours'] = df['delivery_time'] / 60
df

city  delivery_time  couriers  delivery_time_hours
Msc     Moscow             25     11440             0.416667
Krd  Krasnodar             29       784             0.483333
Blg   Belgorod             32       112             0.533333
Kzn      Kazan             30       998             0.500000

In [41]:
# При дропе колонок необходимо в том или ином виде перезаписывать данные в исходном датафрейме

df.drop(['delivery_time_hours'], axis = 1, inplace=True)
# df.drop(['delivery_time_hours'], axis = 'columns', inplace=True)

In [42]:
df

city  delivery_time  couriers
Msc     Moscow             25     11440
Krd  Krasnodar             29       784
Blg   Belgorod             32       112
Kzn      Kazan             30       998

In [43]:
df = df.rename(columns={'couriers': 'num_of_couriers'})
df

city  delivery_time  num_of_couriers
Msc     Moscow             25            11440
Krd  Krasnodar             29              784
Blg   Belgorod             32              112
Kzn      Kazan             30              998

In [44]:
# вытаскиваем n - самых больших показателей из колонки - нет нужды в сортировке

df.nlargest(3, 'delivery_time')

city  delivery_time  num_of_couriers
Blg   Belgorod             32              112
Kzn      Kazan             30              998
Krd  Krasnodar             29              784

In [46]:
# вытаскиваем n - самых больших маленьких из колонки - нет нужды в сортировке

df.nsmallest(3, 'delivery_time')

city  delivery_time  num_of_couriers
Msc     Moscow             25            11440
Krd  Krasnodar             29              784
Kzn      Kazan             30              998

In [47]:
df.columns = ['City', 'Delivery_Time', 'Num_of_Couriers']

In [48]:
df

City  Delivery_Time  Num_of_Couriers
Msc     Moscow             25            11440
Krd  Krasnodar             29              784
Blg   Belgorod             32              112
Kzn      Kazan             30              998

### Задание

Файл содержит таблицу, которая состоит из следующих колонок:
- date (дата);
-
vendor_id (уникальный идентификатор ресторана);
- chain_id (уникальный идентификатор сети, в которую входит
ресторан);
-
city_id (идентификатор города); - spec (специализация ресторана);
-
successful_orders (количество успешных заказов);
-
fail_orders (количество неуспешных заказов).
Ответьте на следующие вопросы на основе информации,
содержащейся в этой таблице.
1. Сколько уникальных городов представлено в этом датафрейме?
2. Сколько ресторанов в таблице специализируются на рыбе?
3. Сколько колонок в датафрейме имеют тип данных float64?
4. Сколько дней у ресторана с идентификатором 40065 было менее 20
успешных заказов?
Ответ введите целыми числами через запятую.

In [49]:
data = pd.read_csv('orders.csv')

In [51]:
data.head()

date  vendor_id  chain_id  city_id     spec  successful_orders  \
0  2019-07-02      40065      7501       23     Суши               54.0   
1  2019-08-27      48058     33226       23   Шаурма                0.0   
2  2019-09-25      35430     26220       25    Пицца                2.0   
3  2019-09-21      56553     38601       23  Шашлыки                1.0   
4  2019-09-21      43919     30984       25     Суши                6.0   

   fail_orders  
0          1.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0

In [59]:
# Сколько уникальных городов представлено в этом датафрейме?

data[['city_id']].nunique()

city_id    4
dtype: int64

In [70]:
#Сколько ресторанов в таблице специализируются на рыбе?

data[(data.spec == 'Рыба')][['spec', 'vendor_id']].nunique()

spec          1
vendor_id    18
dtype: int64

In [79]:
# Сколько колонок в датафрейме имеют тип данных float64?

data.dtypes

date                  object
vendor_id              int64
chain_id               int64
city_id                int64
spec                  object
successful_orders    float64
fail_orders          float64
dtype: object

In [83]:
# Сколько дней у ресторана с идентификатором 40065 было менее 20 успешных заказов? 
# Ответ введите целыми числами через запятую.

data[(data.vendor_id == 40065) & (data.fail_orders < 20)]

date  vendor_id  chain_id  city_id  spec  successful_orders  \
0      2019-07-02      40065      7501       23  Суши               54.0   
1477   2019-07-29      40065      7501       23  Суши               12.0   
2678   2019-08-28      40065      7501       23  Суши               19.0   
2679   2019-08-11      40065      7501       23  Суши               20.0   
3263   2019-09-15      40065      7501       23  Суши               14.0   
...           ...        ...       ...      ...   ...                ...   
94433  2019-07-14      40065      7501       23  Суши               17.0   
94541  2019-08-22      40065      7501       23  Суши               32.0   
94722  2019-09-19      40065      7501       23  Суши               36.0   
95036  2019-07-01      40065      7501       23  Суши               15.0   
95608  2019-08-12      40065      7501       23  Суши               22.0   

       fail_orders  
0              1.0  
1477           0.0  
2678           0.0  
2679           0.0  
3263           0.0  
...            ...  
94433          0.0  
94541          0.0  
94722          1.0  
95036          2.0  
95608          0.0  

[121 rows x 7 columns]